### ISSUE TITLE
Issue with HTML/PHP

### ISSUE THREAD

**Issue by mtruitt** [kokororin/vscode-phpfmt#44]
When HTML is present such as WordPress. Saving repeatedly will force specific things to keep getting pushed. 
For example:
`<html <?php language_attributes();?>>`

Every time you save the space between `<html` and `<?php language_attributes();?>` increases.

This is even using:
`"phpfmt.passes": [
        "AlignPHPCode"
    ]`

**Comment by TheDutchCoder** [comment]
To add to this: it gets even worse when you have blocks of PHP in your HTML.

They'll be forced to the start of the line, instead of keeping proper spacing.

Bad:
![image](https://user-images.githubusercontent.com/1668207/44152650-1047fa2c-a074-11e8-9416-258c624b4c70.png)

Good:
![image](https://user-images.githubusercontent.com/1668207/44152662-18626a30-a074-11e8-871c-2d7d631bdac9.png)

**Comment by RiFi2k** [comment]
I made [this extension](https://marketplace.visualstudio.com/items?itemName=rifi2k.format-html-in-php) because I could never find anything that would get them both right. You can still keep this extension for the PHP but the other one will gracefully handle the HTML without getting in the way if you disable the settings for this to format it.

**Comment by smlombardi** [comment]
Yes, I've also found questionable formatting choices.  Why would it do this:

### BEFORE
<img width="548" alt="before" src="https://user-images.githubusercontent.com/835148/46552033-638bcc80-c8a7-11e8-9586-d753993ed6af.png">

### AFTER
<img width="551" alt="after" src="https://user-images.githubusercontent.com/835148/46552043-6dadcb00-c8a7-11e8-8a7d-699a699397fd.png">
