### ISSUE TITLE
PHPDocTypesToFunctionTypehint adds ending comment characters after function

### ISSUE THREAD

**Issue by elliotboney** [kokororin/vscode-phpfmt#48]
When using the pass `PHPDocTypesToFunctionTypehint` phpfmt adds unwanted characters after the function declaration

Before running:
![image](https://user-images.githubusercontent.com/2795952/45269364-7cdd5c80-b452-11e8-9b44-4cfd396b537c.png)

After running:
![image](https://user-images.githubusercontent.com/2795952/45269365-85359780-b452-11e8-9926-d752225f49d9.png)

**Comment by Ceremony64** [comment]
The issue is worse:
When you do not define a return type, it'll look like the screenshot above.
However, with it defined, repeated formatting the code will also break the code.

Example starting code:
```php
/**
 * @param  bool   $bool
 * @param  Custom $class
 * @return bool
 */
function testFunction($bool, $class)
{
    return $bool;
}
```

First formatting:
```php
/**
 * @param  bool   $bool
 * @param  Custom $class
 * @return bool
 */
function testFunction($bool, custom $class)
: bool {
    return $bool;
}
```

Second formatting:
```php
/**
 * @param  bool   $bool
 * @param  Custom $class
 * @return bool
 */
function testFunction($bool, customcustom $class)
: bool:bool {
    return $bool;
}
```

Since the code is no longer valid, a third formatting is no longer possible.

Also, when parameters are objects, their classname also gets repeated with each formatting. Weirdly, the type bool does not get added to the variable `$bool` like in the screenshot. I guess something changed in the last 4 years?

Also, this only applies to regular functions but not for methods within a class. In classes, it doesn't add any typehints to the method. Not sure if this is intended either?
